workspace: "exp/ecapa_tdnn_softmax"
trial_path: "data/vox1_clean.txt"
keep_loss_weight: True
checkpoint_path: None
num_workers: 40
num_shot: 1
batch_size: 320
save_top_k: 30
score_save_path: None
train_dataset:
        name: "Train_Dataset"
        train_csv_path: "data/train.csv"
        noise_csv_path: "data/noise.csv"
        sample_rate: 16000
        second: 2
        spk_utt: 100
trainer:
        max_epochs: 25
        gpus: 3
        accelerator: dp
        check_val_every_n_epoch: 1
feature: 
        name: "Mel_Spectrogram"
        coef: 0.97
        n_fft: 512
        win_length: 400
        hop: 160
        n_mels: 80
        requires_grad: True
backbone: 
        name: "ecapa_tdnn"
        embedding_dim: 192
        num_channels: 512
        n_mels: 80
loss:
        name: "softmax"
        embedding_dim: 192
optim:
        name: "Adam"
        lr: 0.01
        weight_decay: 0.0
warmup_step: 500
schedule:
        name: "StepLR"
        gamma: 0.3
        step_size: 3
