workspace: "exp/aam"
trial_path: "data/vox1_clean.txt"
keep_loss_weight: True
checkpoint_path: None
num_workers: 64
num_shot: 3
batch_size: 2
save_top_k: 30
score_save_path: None
train_dataset:
        name: "Few_Shot_Dataset"
        train_csv_path: "data/train.csv"
        noise_csv_path: "data/noise.csv"
        num_shot: 3
        sample_rate: 16000
        second: 2
        spk_utt: 100
        num_per_speaker: 1
trainer:
        max_epochs: 5
        gpus: 1
        accelerator: dp
        check_val_every_n_epoch: 1
feature: 
        name: "Mel_Spectrogram"
        coef: 0.97
        n_fft: 512
        win_length: 400
        hop: 160
        n_mels: 64
        requires_grad: True
backbone: 
        name: "resnet34"
        embedding_dim: 256
        num_channels: [1, 32, 64, 128, 256]
        n_mels: 64
        pooling_type: "TSP"
loss:
        name: "softmax"
        embedding_dim: 256
        margin: 0.2
        scale: 30
optim:
        name: "Adam"
        lr: 0.01
        weight_decay: 0.0
warmup_step: 500
schedule:
        name: "StepLR"
        gamma: 0.5
        step_size: 3
